# Generated by Django 5.2.12 on 2026-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('funder', models.CharField(max_length=200)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('journal_or_source', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('journal', 'Journal Article'), ('book', 'Book Chapter'), ('working', 'Working Paper'), ('media', 'Media Article')], default='journal', max_length=20)),
                ('link', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField()),
                ('research_interests', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('scholar_url', models.URLField(blank=True)),
                ('orcid_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Principal supervisor / Co-supervisor', max_length=100)),
                ('topic', models.CharField(blank=True, max_length=250)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', 'course_name'],
            },
        ),
    ]
