# Generated by Django 5.2.12 on 2026-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='featured',
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('published_paper', 'Published Paper'), ('media_article', 'Media Article'), ('book_chapter', 'Book Chapter'), ('journal_reviewer', 'Journal Reviewer'), ('journal_published', 'Journal Published'), ('working_paper', 'Working Paper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_or_source',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
