# Generated by Django 5.2.12 on 2026-03-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_publication_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
