# Generated by Django 5.2.12 on 2026-03-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_siteprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='positions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='professional_education',
            field=models.TextField(blank=True),
        ),
    ]
