# Generated by Django 5.2.12 on 2026-03-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_siteprofile_education_siteprofile_positions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('year_range', models.CharField(blank=True, help_text='e.g. 2021–Present', max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g. Editorial, Conference, Grant Review', max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', '-title'],
            },
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='bluesky_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='cssn_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='researchgate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='scopus_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='ssrn_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='webofscience_url',
            field=models.URLField(blank=True),
        ),
    ]
