# Generated by Django 5.2.12 on 2026-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract_image',
            field=models.ImageField(blank=True, null=True, upload_to='abstract_images/'),
        ),
    ]
