# Generated by Django 5.2.12 on 2026-04-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_publication_abstract_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citation_count',
            field=models.PositiveIntegerField(blank=True, help_text='Google Scholar citation count', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='rank',
            field=models.CharField(blank=True, help_text='e.g. A*, A, B, C (ABDC) or A (APSA)', max_length=20),
        ),
    ]
