# Generated by Django 5.2.12 on 2026-04-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_teachingresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='current_position',
            field=models.CharField(blank=True, help_text='Current position or job title of the graduate (for completed supervisions)', max_length=300),
        ),
    ]
