# Generated by Django 5.2.12 on 2026-04-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_add_current_position_to_supervision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervision',
            name='status',
            field=models.CharField(choices=[('Current', 'Current'), ('Completed', 'Completed')], default='Current', max_length=100),
        ),
    ]
