# Generated by Django 5.2.12 on 2026-04-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_supervision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, help_text='DOI without https://doi.org/', max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, help_text='e.g. 123–138', max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='reference_apa7',
            field=models.TextField(blank=True, help_text='Optional manual APA7 reference override'),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
