# Generated by Django 5.2.12 on 2026-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_publication_doi_publication_issue_publication_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]