# Generated by Django 5.2.12 on 2026-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_supervision_completed_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='rank',
            field=models.CharField(blank=True, help_text='e.g. FT50, A*, A, B, C (ABDC) or A (APSA)', max_length=20),
        ),
    ]
