# Generated by Django 5.2.12 on 2026-05-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_publication_featured_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['ordering']},
        ),
    ]
