# Generated by Django 5.2.12 on 2026-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_publication_journaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='rank',
            field=models.CharField(blank=True, help_text='e.g. A*, A, B, C (ABDC) or A (APSA)', max_length=20),
        ),
    ]
